-- Generated by scripts/import-iptv.mjs on 2026-09-10
-- Source: https://iptv-org.github.io/api/ (index of publicly reachable streams)
-- Filters: countries=BD languages=ben official-only probed=alive
--
-- Channels on the upstream dmca/nsfw blocklist are never emitted.
-- Re-run the script to refresh: live stream URLs rot, typically within months.

begin;

insert into public.categories (slug, name, kind, sort_order) values
  ('news', 'News', 'live_tv', 10),
  ('kids-tv', 'Kids & Cartoons', 'live_tv', 40),
  ('music-tv', 'Music', 'live_tv', 60),
  ('religious-tv', 'Religious', 'live_tv', 70),
  ('entertainment', 'Entertainment', 'live_tv', 20)
on conflict (slug) do update
  set name = excluded.name,
      kind = excluded.kind,
      sort_order = excluded.sort_order;

insert into public.channels
  (slug, name, description, logo_url, stream_url, stream_protocol, stream_headers, category_id, sort_order)
values
  ('ctvn-akd-plus-in', 'CTVN AKD Plus', 'IN · ben · 1080p', 'https://dtil.tmsimg.com/assets/s142754_ld_h15_aa.png?lock=720x540',
   'https://live.legitpro.co.in/ctvnakdplus/index.m3u8', 'hls', null,
   (select id from public.categories where slug = 'news'), 10),
  ('zillarbarta-news-in', 'ZillarBarta News', 'IN · ben', 'https://jiotvimages.cdn.jio.com/dare_images/images/zillarbarta.png',
   'https://server.zillarbarta.com/zillarbarta/index.m3u8', 'hls', null,
   (select id from public.categories where slug = 'news'), 20),
  ('doyel-tv-ca', 'Doyel TV', 'CA · ben', 'https://i.imgur.com/8pR8Q4J.png',
   'https://3d46w.doyeltv.com/memfs/aa3aa6f7-ec12-41a2-8183-a891e157bbf8.m3u8', 'hls', null,
   (select id from public.categories where slug = 'entertainment'), 30),
  ('zb-cartoon-in', 'ZB Cartoon', 'IN · ben · 1080p', 'https://i.imgur.com/BbFNpMr.jpeg',
   'https://server.zillarbarta.com/zbcatun/video.m3u8', 'hls', null,
   (select id from public.categories where slug = 'kids-tv'), 40),
  ('zb-music-in', 'ZB Music', 'IN · ben · 720p', 'https://i.imgur.com/k1nb8u1.jpeg',
   'https://server.zillarbarta.com/zbmusic/index.m3u8', 'hls', null,
   (select id from public.categories where slug = 'music-tv'), 50),
  ('jtbs-classic-in', 'JTBS Classic', 'IN · ben/eng', 'https://jtbsclassic.dpdns.org/logo.png',
   'https://jtbsclassic.dpdns.org/live.m3u8', 'hls', null,
   (select id from public.categories where slug = 'religious-tv'), 60)
on conflict (slug) do update
  set name = excluded.name,
      description = excluded.description,
      logo_url = excluded.logo_url,
      stream_url = excluded.stream_url,
      stream_protocol = excluded.stream_protocol,
      stream_headers = excluded.stream_headers,
      category_id = excluded.category_id,
      sort_order = excluded.sort_order,
      is_active = true;

commit;
