-- ---------------------------------------------------------------------------
-- 0004 -- add 'youtube' to stream_protocol
-- ---------------------------------------------------------------------------
--
-- The other three protocols describe a file the device downloads and decodes
-- itself: Media3 is handed the URL and plays the bytes. 'youtube' is not that.
-- A youtube.com/watch URL serves an HTML page, and the media behind it is only
-- obtainable by defeating a signature scheme that exists precisely to stop you
-- -- which is both against the YouTube Terms of Service and the fastest way to
-- ship a player that breaks without warning every few weeks.
--
-- So this value means something different in kind from its neighbours: HAND
-- THIS OFF, do not decode it. `src/services/externalPlayback.ts` opens it in
-- the YouTube app, where the rights holder gets the view and the ad revenue
-- that pays for the upload being free in the first place. The row is still
-- nothing but a URL the app never touches the bytes of, so the architectural
-- rule in the README holds: it is the destination that changes, not the model.
--
-- Why this is worth a migration at all, rather than a stream_url the app
-- pattern-matches on: a protocol is already the column that answers "how do I
-- play this", every consumer switches on it, and `mp4` vs `youtube` is exactly
-- the same kind of question as `mp4` vs `hls`. Sniffing the hostname instead
-- would put that knowledge in whichever screens happened to need it.
--
-- Alone in its own file on purpose. PostgreSQL will not let a new enum value be
-- USED in the transaction that adds it (it is invisible to other snapshots
-- until commit), and .github/workflows/migrate.yml wraps each file in exactly
-- one transaction -- so 0005 can create columns of this type and the seed files
-- can insert rows carrying the value, but neither could if they lived here.
-- 0002_add_anime_kind.sql is the same shape for the same reason.
--
-- `add value if not exists` makes it safe to apply twice, which matters because
-- `supabase db push`, the migrate workflow and a manual `psql -f` can all have
-- been run against one project.

alter type public.stream_protocol add value if not exists 'youtube';
